/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package main.java.SHS.UI;

import static java.lang.Boolean.*;
import java.text.ParseException;
import java.text.SimpleDateFormat;
import java.util.Date;
import javax.swing.JOptionPane;
import main.java.SHS.Application;
import main.java.SHS.FileHandlers.FileHandler;
import main.java.SHS.FileHandlers.FileName;
import main.java.SHS.FileHandlers.FileRecord;
import main.java.SHS.Services.ApplicationService;
import main.java.SHS.Student_Hostel_System;
import java.util.Calendar;



/**
 *
 * @author User
 */
public class UI_Booking extends javax.swing.JFrame {
    public static int no;
    public static String type;
    public static String furnish;
    public static String price;
    
    /**
     * Creates new form UI_Booking
     */
    public UI_Booking(int no,String type,String Furnish, String price) {
        initComponents();
        UI_Booking.no = no;
        UI_Booking.type = type;
        UI_Booking.furnish = Furnish;
        UI_Booking.price = price;
        RoomLbl.setText("Room No :" + no);
        TypeLbl.setText("Room Type :" + type);
        FurnishLbl.setText("Furnishing :" + furnish);
        PriceLbl.setText("Price/M :" + price);
        etxt.setText(Student_Hostel_System.current_user.getUserEmail());
        pntxt.setText(Student_Hostel_System.current_user.getContact());
    }
    
    
        public UI_Booking(int no,String type,String Furnish, String price, String date) {
        initComponents();
        UI_Booking.no = no;
        UI_Booking.type = type;
        UI_Booking.furnish = Furnish;
        UI_Booking.price = price;
        RoomLbl.setText("Room No :" + no);
        TypeLbl.setText("Room Type :" + type);
        FurnishLbl.setText("Furnishing :" + furnish);
        PriceLbl.setText("Price/M :" + price);
        etxt.setText(Student_Hostel_System.current_user.getUserEmail());
        pntxt.setText(Student_Hostel_System.current_user.getContact());
        ctxt.setText(date);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        TypeLbl = new javax.swing.JLabel();
        PriceLbl = new javax.swing.JLabel();
        jPanel2 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        etxt = new javax.swing.JTextField();
        jLabel8 = new javax.swing.JLabel();
        pntxt = new javax.swing.JTextField();
        jLabel6 = new javax.swing.JLabel();
        lstxt = new javax.swing.JComboBox<>();
        ctxt = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        bbut = new javax.swing.JButton();
        sbut = new javax.swing.JButton();
        RoomLbl = new javax.swing.JLabel();
        FurnishLbl = new javax.swing.JLabel();
        jPanel3 = new javax.swing.JPanel();
        jLabel5 = new javax.swing.JLabel();
        BackBtn = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setBackground(new java.awt.Color(217, 225, 230));

        TypeLbl.setFont(new java.awt.Font("URWEgyptienneT", 0, 18)); // NOI18N
        TypeLbl.setForeground(new java.awt.Color(92, 128, 188));
        TypeLbl.setText("Room Type :");

        PriceLbl.setFont(new java.awt.Font("URWEgyptienneT", 0, 18)); // NOI18N
        PriceLbl.setForeground(new java.awt.Color(92, 128, 188));
        PriceLbl.setText("Price/M :");

        jPanel2.setBackground(new java.awt.Color(92, 128, 188));
        jPanel2.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        jPanel2.setForeground(new java.awt.Color(92, 128, 188));
        jPanel2.setOpaque(false);

        jLabel1.setFont(new java.awt.Font("SimHei", 0, 16)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(92, 128, 188));
        jLabel1.setText("Enter Your Details");

        jLabel2.setFont(new java.awt.Font("Trebuchet MS", 0, 14)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(92, 128, 188));
        jLabel2.setText("E-mail *");

        etxt.setForeground(new java.awt.Color(92, 128, 188));
        etxt.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                etxtActionPerformed(evt);
            }
        });

        jLabel8.setFont(new java.awt.Font("Trebuchet MS", 0, 14)); // NOI18N
        jLabel8.setForeground(new java.awt.Color(92, 128, 188));
        jLabel8.setText("Phone Number *");

        pntxt.setForeground(new java.awt.Color(92, 128, 188));
        pntxt.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                pntxtActionPerformed(evt);
            }
        });

        jLabel6.setFont(new java.awt.Font("Trebuchet MS", 0, 14)); // NOI18N
        jLabel6.setForeground(new java.awt.Color(92, 128, 188));
        jLabel6.setText("Length of Stay *");

        lstxt.setForeground(new java.awt.Color(92, 128, 188));
        lstxt.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "1 month", "3 months", "6 months", "12 months" }));
        lstxt.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                lstxtActionPerformed(evt);
            }
        });

        ctxt.setForeground(new java.awt.Color(92, 128, 188));
        ctxt.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ctxtActionPerformed(evt);
            }
        });

        jLabel3.setFont(new java.awt.Font("Trebuchet MS", 0, 14)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(92, 128, 188));
        jLabel3.setText("Check in Date (dd-mm-yyyy) *");

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(38, 38, 38)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 176, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel6, javax.swing.GroupLayout.PREFERRED_SIZE, 135, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(lstxt, javax.swing.GroupLayout.PREFERRED_SIZE, 157, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(etxt, javax.swing.GroupLayout.PREFERRED_SIZE, 161, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(29, 29, 29)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel2Layout.createSequentialGroup()
                                .addGap(6, 6, 6)
                                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(pntxt, javax.swing.GroupLayout.PREFERRED_SIZE, 161, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(ctxt, javax.swing.GroupLayout.PREFERRED_SIZE, 161, javax.swing.GroupLayout.PREFERRED_SIZE)))
                            .addComponent(jLabel8, javax.swing.GroupLayout.PREFERRED_SIZE, 167, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel3)))
                    .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 176, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(21, Short.MAX_VALUE))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(21, 21, 21)
                .addComponent(jLabel1)
                .addGap(18, 18, 18)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(jLabel8))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(etxt, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(pntxt, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGap(33, 33, 33)
                        .addComponent(jLabel3))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jLabel6)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lstxt, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(ctxt, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(30, Short.MAX_VALUE))
        );

        bbut.setBackground(new java.awt.Color(92, 128, 188));
        bbut.setFont(new java.awt.Font("Yu Gothic UI Semibold", 0, 14)); // NOI18N
        bbut.setForeground(new java.awt.Color(217, 225, 230));
        bbut.setText("BACK");
        bbut.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bbutActionPerformed(evt);
            }
        });

        sbut.setBackground(new java.awt.Color(92, 128, 188));
        sbut.setFont(new java.awt.Font("Yu Gothic UI Semibold", 0, 14)); // NOI18N
        sbut.setForeground(new java.awt.Color(217, 225, 230));
        sbut.setText("Apply for Room");
        sbut.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                sbutActionPerformed(evt);
            }
        });

        RoomLbl.setFont(new java.awt.Font("URWEgyptienneT", 0, 18)); // NOI18N
        RoomLbl.setForeground(new java.awt.Color(92, 128, 188));
        RoomLbl.setText("Room No :");

        FurnishLbl.setFont(new java.awt.Font("URWEgyptienneT", 0, 18)); // NOI18N
        FurnishLbl.setForeground(new java.awt.Color(92, 128, 188));
        FurnishLbl.setText("Furnishing : ");

        jPanel3.setBackground(new java.awt.Color(92, 128, 188));

        jLabel5.setFont(new java.awt.Font("Yu Gothic UI Semibold", 0, 24)); // NOI18N
        jLabel5.setForeground(new java.awt.Color(217, 225, 230));
        jLabel5.setText("Hostel Booking Application");

        BackBtn.setFont(new java.awt.Font("Yu Gothic UI Semibold", 0, 12)); // NOI18N
        BackBtn.setForeground(new java.awt.Color(217, 225, 228));
        BackBtn.setText("< Back");
        BackBtn.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                BackBtnMouseClicked(evt);
            }
        });

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel3Layout.createSequentialGroup()
                .addGap(27, 27, 27)
                .addComponent(BackBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 62, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 66, Short.MAX_VALUE)
                .addComponent(jLabel5)
                .addGap(153, 153, 153))
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addGap(14, 14, 14)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel5)
                    .addComponent(BackBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(17, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(bbut, javax.swing.GroupLayout.PREFERRED_SIZE, 175, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(34, 34, 34)
                .addComponent(sbut, javax.swing.GroupLayout.PREFERRED_SIZE, 180, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(113, 113, 113))
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(73, 73, 73)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(RoomLbl, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(FurnishLbl, javax.swing.GroupLayout.DEFAULT_SIZE, 236, Short.MAX_VALUE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(TypeLbl, javax.swing.GroupLayout.PREFERRED_SIZE, 249, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(PriceLbl, javax.swing.GroupLayout.PREFERRED_SIZE, 249, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(44, Short.MAX_VALUE))
            .addComponent(jPanel3, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addComponent(jPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(31, 31, 31)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(RoomLbl)
                    .addComponent(TypeLbl))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(FurnishLbl)
                    .addComponent(PriceLbl))
                .addGap(18, 18, 18)
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(sbut, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(bbut, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(29, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void sbutActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_sbutActionPerformed
        
        FileHandler fHandler = new FileHandler(FileName.APPLICATIONS);
        // Validation
        
        if( etxt.getText().isEmpty() || pntxt.getText().isEmpty() || ctxt.getText().isEmpty() || lstxt.getSelectedItem()==null){
            JOptionPane.showMessageDialog(null,"Text Field Cannot Be Empty!" , "TextField Empty",JOptionPane.ERROR_MESSAGE,null);
        }else{
            int result = JOptionPane.showConfirmDialog(this, "Confirm Room?", "Confirmation",
                    JOptionPane.YES_NO_OPTION, JOptionPane.QUESTION_MESSAGE,null);
        if (result==JOptionPane.YES_OPTION){
            int StudentId = Student_Hostel_System.current_user.getUserId();
            String StudentName = Student_Hostel_System.current_user.getUsername();
            int RoomNumber = no;
            String cdate = ctxt.getText();
            String email = etxt.getText();
            String phone = pntxt.getText();
            String los = lstxt.getSelectedItem().toString();
            String status = "Pending";
            if(bookingvalidation (email,phone,cdate)){
                // Extract the numeric part from the string
                String numericPart = los.split(" ")[0];

                // Parse the numeric part into an integer
                int intlos = Integer.parseInt(numericPart);

                SimpleDateFormat dateFormat = new SimpleDateFormat("dd-MM-yyyy");
            try {
                Date startDate = dateFormat.parse(cdate);

                // Check if the check-in date is after the current date
                    Date currentDate = new Date();

                // Create a Calendar instance and set the start date
                Calendar calendar = Calendar.getInstance();
                calendar.setTime(startDate);
                // Add the length of stay (in months) to the start date
                calendar.add(Calendar.MONTH, intlos);
                // Get the check-out date
                Date checkOutDate = calendar.getTime();
                    if (checkOutDate.before(currentDate)) {
                        JOptionPane.showMessageDialog(null, "Check-in date cannot be in the past!", "Invalid Date",
                                JOptionPane.ERROR_MESSAGE, null);
                        return; // Stop further processing
                    }
                // Format the check-out date as a string
                String formattedCheckOutDate = dateFormat.format(checkOutDate);


                    // Create application object
                    Application application = new Application(fHandler.GenerateID(), StudentName, StudentId, RoomNumber, cdate, formattedCheckOutDate, intlos, status);

                    // Send application
                    ApplicationService applicationService = new ApplicationService();
                    applicationService.sendApplication(application);



                    if (!applicationService.checkExistingApplication(Student_Hostel_System.current_user.getUsername())) {
                    JOptionPane.showMessageDialog(null,"No existing booking. Make a booking first!" , "Error",JOptionPane.ERROR_MESSAGE,null);
                    return; // Stop further processing
                    }
                    JOptionPane.showMessageDialog(null, "Application Successfully sent! Await for approval from Admin.");
                    this.setVisible(false);
                        UI_Applications UIA = new UI_Applications();
                        UIA.setVisible(true);
                                }

                             catch (java.text.ParseException e) {
                                e.printStackTrace();
                            }
                        }}
        else{
        UI_Student_Main us = new UI_Student_Main();
        us.setVisible(true);
        this.dispose();
        }
        }
    }//GEN-LAST:event_sbutActionPerformed

    private void bbutActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bbutActionPerformed
        // Hide the current window
        this.setVisible(false);

    // ...
    UI_Rooms s = new UI_Rooms();
    s.refreshTable(); // Refresh the table data
    s.setVisible(true);
    // ...
    }//GEN-LAST:event_bbutActionPerformed

    private void ctxtActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ctxtActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_ctxtActionPerformed

    private void lstxtActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_lstxtActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_lstxtActionPerformed

    private void pntxtActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_pntxtActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_pntxtActionPerformed

    private void etxtActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_etxtActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_etxtActionPerformed

    private void BackBtnMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_BackBtnMouseClicked
        // Hide the current window
        this.setVisible(false);

        // ...
        UI_Rooms s = new UI_Rooms();
        s.refreshTable(); // Refresh the table data
        s.setVisible(true);
        // ...
    }//GEN-LAST:event_BackBtnMouseClicked
      private boolean bookingvalidation(String email, String phone, String cdate){
        if(!email.matches("^[\\w-\\.]+@([\\w-]+\\.)+[\\w-]{2,4}$")){
            JOptionPane.showMessageDialog(this,"Invalid email!","Wrong Format",JOptionPane.ERROR_MESSAGE,null);
            return false;
        }
        if(!cdate.matches("\\d{2}-\\d{2}-\\d{4}")){
            JOptionPane.showMessageDialog(this,"Invalid check in date!","Wrong Format",JOptionPane.ERROR_MESSAGE,null);
            return false;
        }
        return true;
    }
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(UI_Booking.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(UI_Booking.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(UI_Booking.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(UI_Booking.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new UI_Booking(no,type,furnish,price).setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel BackBtn;
    private javax.swing.JLabel FurnishLbl;
    private javax.swing.JLabel PriceLbl;
    private javax.swing.JLabel RoomLbl;
    private javax.swing.JLabel TypeLbl;
    private javax.swing.JButton bbut;
    private javax.swing.JTextField ctxt;
    private javax.swing.JTextField etxt;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JComboBox<String> lstxt;
    private javax.swing.JTextField pntxt;
    private javax.swing.JButton sbut;
    // End of variables declaration//GEN-END:variables
}
