/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package main.java.SHS.UI;

import main.java.SHS.Application;
import main.java.SHS.Room;
import main.java.SHS.Payment;
import main.java.SHS.Services.ApplicationService;
import main.java.SHS.Services.RoomService;
import main.java.SHS.Services.PaymentService;
import main.java.SHS.Student_Hostel_System;
import java.text.SimpleDateFormat;
import java.util.Date;
import javax.swing.JOptionPane;
import main.java.SHS.BookedRoom;
import main.java.SHS.FileHandlers.FileHandler;
import main.java.SHS.FileHandlers.FileName;
import main.java.SHS.Services.BookedRoomService;


/**
 *
 * @author User
 */
public class UI_Payment extends javax.swing.JFrame {
    int StudentID;
    int RoomID;
    int AppID;
    int total;
    String formattedDate;
    /**
     * Creates new form UI_Payment
     */

    public UI_Payment() {
        initComponents();

        ApplicationService applicationService = new ApplicationService();
        Application application = applicationService.getApplication(Student_Hostel_System.current_user.getUsername());

        RoomService roomservice = new RoomService();
        Room room = roomservice.getRoom(application.getRoomId());

        StudentID = application.getStudentId();
        RoomID = application.getRoomId();
        AppID = application.getApplicationID();

        LOSLbl.setText("Length of Stay: " + application.getLos() + " Months");
        RentLbl.setText("Monthly Rent: RM" + room.getPrice());

        total = application.getLos() * room.getPrice();
        TotalLbl.setText("Total Payment: RM" + total);

        // Set DateLbl to today's date
        SimpleDateFormat dateFormat = new SimpleDateFormat("dd-MM-yyyy");
        Date currentDate = new Date();
        this.formattedDate = dateFormat.format(currentDate);
        DateLbl.setText("Date: " + this.formattedDate);
    }


    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jPanel2 = new javax.swing.JPanel();
        DateLbl = new javax.swing.JLabel();
        DateLbl1 = new javax.swing.JLabel();
        DateLbl2 = new javax.swing.JLabel();
        DateLbl3 = new javax.swing.JLabel();
        CardNumber = new javax.swing.JTextField();
        ExpDate = new javax.swing.JTextField();
        CVV = new javax.swing.JTextField();
        jLabel5 = new javax.swing.JLabel();
        PayBtn = new javax.swing.JButton();
        CancelBtn = new javax.swing.JButton();
        LOSLbl = new javax.swing.JLabel();
        RentLbl = new javax.swing.JLabel();
        TotalLbl = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setBackground(new java.awt.Color(217, 225, 228));

        jPanel2.setBackground(new java.awt.Color(92, 128, 188));

        DateLbl.setFont(new java.awt.Font("Yu Gothic UI Semibold", 0, 14)); // NOI18N
        DateLbl.setForeground(new java.awt.Color(217, 225, 228));
        DateLbl.setText("Date : ");

        DateLbl1.setFont(new java.awt.Font("Yu Gothic UI Semibold", 0, 14)); // NOI18N
        DateLbl1.setForeground(new java.awt.Color(217, 225, 228));
        DateLbl1.setText("CARD NUMBER : ");

        DateLbl2.setFont(new java.awt.Font("Yu Gothic UI Semibold", 0, 14)); // NOI18N
        DateLbl2.setForeground(new java.awt.Color(217, 225, 228));
        DateLbl2.setText("EXP DATE : ");

        DateLbl3.setFont(new java.awt.Font("Yu Gothic UI Semibold", 0, 14)); // NOI18N
        DateLbl3.setForeground(new java.awt.Color(217, 225, 228));
        DateLbl3.setText("CVV / CVC :");

        CardNumber.setFont(new java.awt.Font("Yu Gothic UI Semibold", 0, 12)); // NOI18N
        CardNumber.setText("XXXX-XXXX-XXXX-XXXX");
        CardNumber.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                CardNumberActionPerformed(evt);
            }
        });

        ExpDate.setFont(new java.awt.Font("Yu Gothic UI Semibold", 0, 12)); // NOI18N
        ExpDate.setText("XX/XX");
        ExpDate.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ExpDateActionPerformed(evt);
            }
        });

        CVV.setFont(new java.awt.Font("Yu Gothic UI Semibold", 0, 12)); // NOI18N
        CVV.setText("XXX");
        CVV.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                CVVActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addComponent(DateLbl, javax.swing.GroupLayout.PREFERRED_SIZE, 129, javax.swing.GroupLayout.PREFERRED_SIZE))
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(44, 44, 44)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addComponent(DateLbl1, javax.swing.GroupLayout.PREFERRED_SIZE, 129, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addComponent(CardNumber)
                        .addGap(45, 45, 45))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(DateLbl2, javax.swing.GroupLayout.PREFERRED_SIZE, 129, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(ExpDate, javax.swing.GroupLayout.PREFERRED_SIZE, 155, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 30, Short.MAX_VALUE)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(DateLbl3, javax.swing.GroupLayout.PREFERRED_SIZE, 129, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(CVV, javax.swing.GroupLayout.PREFERRED_SIZE, 155, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(44, 44, 44))))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addComponent(DateLbl, javax.swing.GroupLayout.PREFERRED_SIZE, 29, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(DateLbl1, javax.swing.GroupLayout.PREFERRED_SIZE, 29, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(CardNumber, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(30, 30, 30)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(DateLbl2, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 29, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(DateLbl3, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 29, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(CVV, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(ExpDate, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(0, 42, Short.MAX_VALUE))
        );

        jLabel5.setFont(new java.awt.Font("Yu Gothic UI Semibold", 0, 24)); // NOI18N
        jLabel5.setForeground(new java.awt.Color(92, 128, 188));
        jLabel5.setText("PAYMENT");

        PayBtn.setText("Pay");
        PayBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                PayBtnActionPerformed(evt);
            }
        });

        CancelBtn.setText("Cancel");
        CancelBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                CancelBtnActionPerformed(evt);
            }
        });

        LOSLbl.setFont(new java.awt.Font("Yu Gothic UI Semibold", 0, 14)); // NOI18N
        LOSLbl.setForeground(new java.awt.Color(92, 128, 188));
        LOSLbl.setText("Length Of Stay : ");

        RentLbl.setFont(new java.awt.Font("Yu Gothic UI Semibold", 0, 14)); // NOI18N
        RentLbl.setForeground(new java.awt.Color(92, 128, 188));
        RentLbl.setText("Rent Per Month : ");

        TotalLbl.setFont(new java.awt.Font("Yu Gothic UI Semibold", 0, 18)); // NOI18N
        TotalLbl.setForeground(new java.awt.Color(92, 128, 188));
        TotalLbl.setText("Total Payment : ");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addComponent(CancelBtn)
                .addGap(100, 100, 100)
                .addComponent(PayBtn)
                .addGap(231, 231, 231))
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(268, 268, 268)
                        .addComponent(jLabel5, javax.swing.GroupLayout.PREFERRED_SIZE, 119, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(113, 113, 113)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(LOSLbl, javax.swing.GroupLayout.PREFERRED_SIZE, 209, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(RentLbl, javax.swing.GroupLayout.PREFERRED_SIZE, 209, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(TotalLbl, javax.swing.GroupLayout.PREFERRED_SIZE, 209, javax.swing.GroupLayout.PREFERRED_SIZE)))))
                .addContainerGap(125, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel5, javax.swing.GroupLayout.PREFERRED_SIZE, 43, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(LOSLbl, javax.swing.GroupLayout.PREFERRED_SIZE, 29, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(RentLbl, javax.swing.GroupLayout.PREFERRED_SIZE, 29, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(18, 18, 18)
                        .addComponent(TotalLbl, javax.swing.GroupLayout.PREFERRED_SIZE, 29, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 21, Short.MAX_VALUE)
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(PayBtn)
                    .addComponent(CancelBtn))
                .addGap(16, 16, 16))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void ExpDateActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ExpDateActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_ExpDateActionPerformed

    private void CVVActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_CVVActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_CVVActionPerformed

    private void CancelBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_CancelBtnActionPerformed
        this.setVisible(false);
        UI_Applications UIA = new UI_Applications();
        UIA.setVisible(true);
    }//GEN-LAST:event_CancelBtnActionPerformed

    private void PayBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_PayBtnActionPerformed
    FileHandler paymentfile = new FileHandler(FileName.PAYMENTS);
    FileHandler bookedroomfile = new FileHandler(FileName.BOOKED_ROOM);
    String cardNumber = CardNumber.getText();
    String expDate = ExpDate.getText();
    String cvv = CVV.getText();
    int paymentID;

    if (cardvalidation(cardNumber, expDate, cvv)) {
        // Confirm payment with the user
        int confirmation = JOptionPane.showConfirmDialog(null, "Confirm payment?", "Payment Confirmation", JOptionPane.YES_NO_OPTION);

        if (confirmation == JOptionPane.YES_OPTION) {
            // Create payment object
            paymentID = paymentfile.GenerateID();
            Payment payment = new Payment(paymentID, StudentID, AppID, total, formattedDate);

            // Make payment
            PaymentService paymentService = new PaymentService();
            paymentService.makePayment(payment);

            // Update application status
            ApplicationService applicationService = new ApplicationService();
            Application application = applicationService.getApplication(Student_Hostel_System.current_user.getUsername());
            applicationService.updateApplication(AppID, "Paid");

            // Update room availability
            RoomService roomService = new RoomService();
            Room room = roomService.getRoom(RoomID);
            roomService.updateRoom(room, "Booked");

            // Insert new booked room record
            BookedRoomService bookedRoomService = new BookedRoomService();
            BookedRoom bookedRoom = new BookedRoom(bookedroomfile.GenerateID(), StudentID, Student_Hostel_System.current_user.getUsername(), AppID, paymentID, application.getStartDate(), application.getEndDate(), application.getLos(), "Active", room.getRoomNumber(), room.getRoomType(), room.getFurnish(), "Booked", room.getPrice());
            bookedRoomService.addBookedRoom(bookedRoom);

            // Display payment success message
            JOptionPane.showMessageDialog(null, "Payment successful!", "Payment Confirmation", JOptionPane.INFORMATION_MESSAGE);
            this.setVisible(false);
            UI_Receipt UIR = new UI_Receipt(paymentID);
            UIR.setVisible(true);
        } else {
            // Display payment cancellation message
            JOptionPane.showMessageDialog(null, "Payment cancelled.", "Payment Confirmation", JOptionPane.INFORMATION_MESSAGE);
        }
    }
    }//GEN-LAST:event_PayBtnActionPerformed

    private void CardNumberActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_CardNumberActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_CardNumberActionPerformed

    
    
    private boolean cardvalidation(String card, String date, String code){
        if(!card.matches("\\d{4}-\\d{4}-\\d{4}-\\d{4}")){
            JOptionPane.showMessageDialog(this,"Invalid card Number!","Wrong Format",JOptionPane.ERROR_MESSAGE,null);
            return false;
        }
        if(!date.matches("\\d{2}/\\d{2}")){
            JOptionPane.showMessageDialog(this,"Invalid expiry date!","Wrong Format",JOptionPane.ERROR_MESSAGE,null);
            return false;
        }
        if(!code.matches("\\d{3}")){
            JOptionPane.showMessageDialog(this,"Invalid CVV/CVC code!","Wrong Format",JOptionPane.ERROR_MESSAGE,null);
            return false;
        }
        return true;
    }
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(UI_Payment.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(UI_Payment.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(UI_Payment.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(UI_Payment.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new UI_Payment().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextField CVV;
    private javax.swing.JButton CancelBtn;
    private javax.swing.JTextField CardNumber;
    private javax.swing.JLabel DateLbl;
    private javax.swing.JLabel DateLbl1;
    private javax.swing.JLabel DateLbl2;
    private javax.swing.JLabel DateLbl3;
    private javax.swing.JTextField ExpDate;
    private javax.swing.JLabel LOSLbl;
    private javax.swing.JButton PayBtn;
    private javax.swing.JLabel RentLbl;
    private javax.swing.JLabel TotalLbl;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    // End of variables declaration//GEN-END:variables
}
